test-kitchen/kitchen-dokken

README.md

Previous version wasn't parseable as YAML

Re-indent example .kitchen.yml

---

lib/kitchen/transport/dokken.rb

Allow override of host ip

---

lib/kitchen/driver/dokken.rb

See #16 
Added; hostname, binds, links, cap_add, cap_drop, security_opt, network_mode

Add common docker run args

---

lib/kitchen/provisioner/dokken.rb

Reverts someara/kitchen-dokken#31

Revert "Set the chef log level to be the same as for the kitchen run."

---

LICENSE
kitchen-dokken.gemspec
lib/kitchen/driver/dokken.rb
lib/kitchen/driver/dokken_version.rb
lib/kitchen/transport/dokken.rb

Latest stable not latest from current

By default pull the latest stable release of chef

---

README.md

- Updates the link in `README.md` to point to the proper `.kitchen.yml` file in the docker cookbook.

Updates link to docker cookbook's .kitchen.yml file

---

.kitchen.yml
lib/kitchen/driver/dokken.rb
lib/kitchen/helpers.rb

See https://github.com/someara/kitchen-dokken/issues/117
To use, add the tmpfs key to driver config.  Value can be a string as passed to --tmpfs, an array of those strings, or a hash of path:options pairs.

Add Tmpfs Support

---

lib/kitchen/driver/dokken.rb

Originally I was always doing to just return the error but after reading #95 I incorporated the suggestions.
fixes #95 
Signed-off-by: Ben Abrams <me@benabrams.it>

improving the error message handling with intermediate builder

---

.travis.yml

Test on ruby 2.5.1 and avoid dev dep

---

test/cookbooks/dokken_test/recipes/default.rb

Signed-off-by: tyler-ball <tball@chef.io>

Fix test that is missing license acceptance value

---

lib/kitchen/driver/dokken.rb

Set CI and TEST_KITCHEN environment variables

---

lib/kitchen/driver/dokken.rb

Avoids a bug in `docker-api` 2.0.0 involving fetching containers by name, by listing all containers and filtering in Ruby. 
If the user has many containers, this may be inefficient, but this is a critical bug. Hopefully this will be a temporary fix. An upstream issue has been opened on docker-api.
Fixes #208

Fix for Nil TypeError when Creating Containers

---

.github/workflows/linters.yml
.rubocop.yml
.travis.yml
.yamllint.yml
Berksfile
CODE_OF_CONDUCT.md
Gemfile
Rakefile
kitchen-dokken.gemspec
lib/kitchen/driver/dokken.rb
lib/kitchen/driver/dokken_version.rb
lib/kitchen/helpers.rb
lib/kitchen/provisioner/dokken.rb
lib/kitchen/transport/dokken.rb
metadata.rb
test/cookbooks/dokken_test/attributes/default.rb
test/cookbooks/dokken_test/metadata.rb
test/cookbooks/dokken_test/recipes/default.rb
test/integration/default/inspec/assert_functioning_spec.rb
test/integration/helloagain/inspec/assert_functioning_spec.rb

Add some testing of Cookstyle as well to keep it clean

Require Ruby 2.5 + apply cookstyle linting

---

lib/kitchen/driver/dokken.rb
lib/kitchen/helpers.rb

Allow users to use their own registry for docker rather than
forcing using docker.io
Closes #217

Add 'docker_registry' option

---

kitchen-dokken.gemspec

Support Test Kitchen 3.0

---

README.md
documentation/PODMAN.md

Add podman documentation
Closes #255

Add pod man documentation

---

README.md

Chef blogs have moved to a different set of URLs, hence older link was broken.
https://github.com/test-kitchen/kitchen-dokken/issues/273
If you have not included a conventional commit message this can be fixed on merge.

Updated link to blog

---

CHANGELOG.md
lib/kitchen/driver/dokken_version.rb

Release 2.17.3
- check if ~/.docker/config.json file exists [@evandam](https://github.com/evandam)
If you have not included a conventional commit message this …

Release 2.17.3

---

CHANGELOG.md
lib/kitchen/driver/dokken_version.rb

Release 2.19.1
- Fix login command for Podman [@jmauro](https://github.com/jmauro)
If you have not included a conventional commit message this can be fixed on …

Release 2.19.1

---

.github/workflows/linters.yml
CHANGELOG.md
README.md

Ensure the readme links stay active

Add link checking to GitHub Actions

---

.github/dependabot.yml

Make sure our config is up to date

Setup dependabot to keep GH Actions up to date

---

.markdownlint.yaml

Signed-off-by: Dan Webb <dan.webb@damacus.io>

fix(lint) add another mdl ignore

---

.github/workflows/lint.yml
renovate.json

- Enable Automerge
- disable dependency dashboard
Signed-off-by: Dan Webb <dan.webb@damacus.io>

fix: Update renovate config

---

.github/workflows/lint.yml
.github/workflows/publish.yaml

Signed-off-by: Dan Webb <dan.webb@damacus.io>

fix: Published package name
