lib/kitchen/driver/dokken_version.rb, lib/kitchen/provisioner/dokken.rb, lib/kitchen/transport/dokken.rb
Cool project! I saw Issue #3 and figured it was a good place to take a look around in a kitchen driver. The changes are, in order:
* Make it so the logger gets passed through
* Turn off coloring on the provisioner
* Use the logger append instead of print.
=> Use kitchen logger to keep log files and color output

README.md, lib/kitchen/provisioner/dokken.rb
I needed to get some troubleshooting information from the Chef run with kitchen-dokken, but the provisioner was set to log at warn level.
This PR makes it configurable (default is still warn).
=> allow the log level to be specified in the provisioner configuration

lib/kitchen/transport/dokken.rb
This ensures, that kitchen dokken is working with Docker for Mac
=> read rsync ip from data container

kitchen-dokken.gemspec, lib/kitchen/driver/dokken.rb, lib/kitchen/driver/dokken/helpers.rb, lib/kitchen/transport/dokken.rb
It's probably a weird edge case that only applies to me, I'm sure, but having a config with both this driver and kitchen-docker loaded right now results in a bunch of this:
```
>>>>>> Message: Failed to complete #destroy action: [uninitialized constant Kitchen::Driver::Docker::Error
```
This would rectify that and also bump the docker-api dep. The current 1.26.2 conflicts with the 1.28.0 pin in the [docker cookbook](https://github.com/chef-cookbooks/docker/blob/master/libraries/_autoload.rb#L2). I don't know the history of the gem, though, so maybe it would be better set as `~> 1.28.0` or needs to be left unchanged for specific reasons?
Thanks!
=> Prevent collisions between docker-api and kitchen-docker

lib/kitchen/driver/dokken.rb
Allows `kitchen destroy` to work when you have multiple containers sharing the same work image.
=> 26 multiple suite destroy

lib/kitchen/driver/dokken.rb
Allow port forwarding as kitchen-docker does with the `forward` key. Refs #14
=> 14 add port forwards

lib/kitchen/provisioner/dokken.rb
This duplicates the behavior of the kitchen-docker module.
=> Set the chef log level to be the same as for the kitchen run.

lib/kitchen/transport/dokken.rb
I'm trying to use kitchen-dokken in GitLab CI with docker-based runners, but cookbooks are failing to sync:
```
$ kitchen test
-----> Starting Kitchen (v1.13.2)
-----> Cleaning up any prior instances of <default-centos-7>
-----> Destroying <default-centos-7>...
Finished destroying <default-centos-7> (0m1.30s).
-----> Testing <default-centos-7>
-----> Creating <default-centos-7>...
Finished creating <default-centos-7> (0m3.92s).
-----> Converging <default-centos-7>...
Preparing files for transfer
Preparing dna.json
Resolving cookbook dependencies with Berkshelf 5.2.0...
Removing non-cookbook files before transfer
Preparing validation.pem
Preparing client.rb
Transferring files to <default-centos-7>
ssh: connect to host 0.0.0.0 port 32772: Connection refused
rsync: connection unexpectedly …
```
=> Use data container's IP if unix socket and SSH port is mapped to 0.0.0.0

lib/kitchen/transport/dokken.rb
Modern versions of Docker for Mac do not map the ports directly to the
IP address. After some trial and error, and looking at the Docker for
Mac documentation, the recommended way is to use "localhost".
This commit adds a simple helper that can pretty reliably detect when
you're running Docker for Mac (and Docker for Windows, I'm not sure) and
tells the transport to use "localhost" instead of the IP.
Signed-off-by: Tom Duffield <tom@chef.io>
=> Use localhost if on Docker for Mac

README.md, lib/kitchen/driver/dokken.rb
Chef now publishes minimalist images (~34MB) in size that are usable
with kitchen-dokken. These images match what is available as binaries in
the stable/current channels in packages.chef.io.
Signed-off-by: Tom Duffield <tom@chef.io>
=> Change defualt image to chef/chef

Gemfile, lib/kitchen/driver/dokken.rb, lib/kitchen/driver/dokken/helpers.rb, lib/kitchen/transport/dokken.rb
* Adjust method calls where docker_connection was being sent as the second instead of third argument
* Fall back to a TCP connection if no unix socket is present
* Fall back to SCP if Rsync isn't installed
* Pass around the Dockerfile as a string instead of a file (to get
around issues with Dir.mktmpdir on Windows not always cleaning up
correctly)
With these changes, the included test configs now pass in Windows as well as Linux and MacOS.
There are still some issues when used with Inspec, but those don't appear to be caused by anything in this driver.
=> Add compatibility with Windows

lib/kitchen/provisioner/dokken.rb
A feature I've been using since it's inclusion is Test Kitchen passing along the `TEST_KITCHEN` environment variable along which lets me execute some cookbook code meant for testing. This lets my tests live along side the running code and has proven to be useful. However, since dokken uses a very different provisioner implementation, this is a quick update to get it to pass along environment variables to the executing chef run. 
I do wonder if this could be improved by using the already built-in helpers in TK because [this is where I gleaned this trick from](https://github.com/test-kitchen/test-kitchen/blob/f8f87b8df62ce53aecfb6a1af977fc74daeaa0df/lib/kitchen/configurable.rb#L311-L317) in the configurable section.
=> Pass along ENV variables in the provisioner

lib/kitchen/driver/dokken.rb
This is useful for enterprises that have their own private docker registries using a non-default port. For example, if my registry lives at `my.awesome.docker.registry:8081` and my image is at `ubuntu/xenial` I would then be able to set my image to `my.awesome.docker.registry:8081/ubuntu/ubuntu:xenial` in the `.kitchen.yaml`.
This makes it so you must use a tag if you want to use a port. Otherwise anything after the colon gets interpreted as the tag. This also preserves the default behavior of defaulting to tag `latest` when a port is not passed. Here are the valid uses with this method:
```
image: ubuntu/ubuntu
image: ubuntu/ubuntu:latest
image: my.awesome.docker.registry:8081/ubuntu/ubuntu:latest
```
in other words:
```
image: repo_without_port
image: repo_without_port:tag
image: …
```
=> allow the use of a port number in the image's repo url

lib/kitchen/provisioner/dokken.rb
Use generic `/opt/chef/bin/chef-client` to be backwards compatible up to chef version 10
Fixes #66
=> Use generic chef-client binary

README.md, lib/kitchen/provisioner/dokken.rb
Provides 4 new options to have more control over the provisioner:
chef_binary: Allows to provide a path for the chef-{client, solo, zero} binary to allow
control over what binary to launch
chef_options: Allows to pass extra options to the chef binary call or avoid the default -z option
chef_log_level: Allows to pass the log level for the chef run
chef_output_format: Allows to set the format of the chef output
This also provides a fix for #66
=> provide several options to have more control over the provisioner

lib/kitchen/transport/dokken.rb
As described in https://github.com/someara/kitchen-dokken/issues/70 the `tmpdir` is shared between users. As the file created is set to be only  [modifiable by the owner](https://github.com/someara/kitchen-dokken/compare/master...edupo:fix/non-shared-tmp?expand=1#diff-e50af27eed3b0cc25806cd3c08774f5fL101) this leads to problems when more than one user is using this specific driver on the same computer.
=> Added user to the temporary path for generating keys

lib/kitchen/helpers.rb
This PR will fix https://github.com/someara/kitchen-dokken/issues/84 by instructing dokken driver to mount default boot2docker share folder when docker remote host is created by docker-machine in Windows instead of instructing mount local directory.
Related with https://github.com/docker/machine/issues/1814 and https://github.com/docker/toolbox/issues/607
=> mount default boot2docker shared folder in Windows

README.md, test/cookbooks/dokken_test/recipes/default.rb
fixes #96 
also: 
> Yes, it is written systemd, not system D or System D, or even SystemD. And it isn't system d either. Why? Because it's a system daemon, and under Unix/Linux those are in lower case, and get suffixed with a lower case d. And since systemd manages the system, it's called systemd. It's that simple. But then again, if all that appears too simple to you, call it (but never spell it!) System Five Hundred since D is the roman numeral for 500 (this also clarifies the relation to System V, right?). The only situation where we find it OK to use an uppercase letter in the name (but don't like it either) is if you start a sentence with systemd. On high holidays you may also spell it sÿstëmd. But then again, Système D is not an acceptable spelling and something completely different …
=> 3) readme: systemd requires specific mount

lib/kitchen/driver/dokken.rb
Currently, kitchen-dokken requires `image` to
be configured explicitly (in contrast to
kitchen-{vagrant,docker}, which derive the
image from the platform name, unless specified).
This copies the code snippet from kitchen-dokken
to use the platform name and use a `repo-tag`
name as `repo:tag` docker image.
If the platform name contains no `-`, the
`:latest` tag will be automatically applied.
Examples:
platforms:
- name: debian-9
- name: ubuntu-1604
- name: centos-7
- name: amazon
image: amazonlinux:latest
Fixes: #91
=> Use platform name for image unless specified

.travis.yml, lib/kitchen/provisioner/dokken.rb, lib/kitchen/transport/dokken.rb
STATE:
Cuurently, the retry kitchen-test feature is not supported
CAUSE:
The call function has been copied from an old kitchen-test version
FIX:
Copy the new from kitchen-test and pass over the right exit code
This fix https://github.com/someara/kitchen-dokken/issues/109
=> Add the retry feature

CHANGELOG.md
=> Fix "ports" config in ChangeLog

lib/kitchen/driver/dokken.rb
This resolves https://github.com/someara/kitchen-dokken/issues/121 : Kitchen Dokken suspicious slow when destroying
Kitchen::Driver::Dokken#with_retries was catching NotFoundError.  This generally isn't something to retry on.  Caused long delays when destroying non-existant kitchens or converging when image is not available.
=> Exclude NotFoundError from Errors that Trigger Retries

README.md
As chef did not create images for all versions I found it necessary for tracking down a bug in `chef-client` 12.x to temporarily overwrite this. As it was not in the documentation I had to review source so I added some documentation to make the next person who needs to do this life easier.
=> add a note about using `chef_image` to overwrite an image

lib/kitchen/helpers.rb, test/cookbooks/dokken_test/recipes/default.rb
This attempts to address issue #105.
There appears to be a race condition when creating a directory
and then immediately setting its mode. This turns the two
operations into a single one and avoids the condition.
=> Single operation for directory creation and mode

README.md
Now that I've actually read through the README I see that the project mentions the other project of images. So this makes me wonder if a further PR which mentions these images earlier in the README.
Signed-off-by: Franklin Webber <franklin@chef.io>
=> Adds the mention of Docker Hub to the README

README.md
This saved my time a lot and may save other's as well. Therefore I want to share the knowledge.
I am not sure if this should be automated, though. That's why I am just sending a `readme` change.
Changing the ubuntu image is trivial. I am unsure about always mounting the `/var/cache/apt/archives/` on a different volume. Maybe it's too much things being done behind the scenes.
=> README Update: How to cache apt downloads

.kitchen.yml, .travis.yml, Berksfile, Gemfile, Rakefile, kitchen-dokken.gemspec, lib/kitchen/driver/dokken.rb, lib/kitchen/driver/dokken_version.rb, lib/kitchen/helpers.rb, lib/kitchen/provisioner/dokken.rb, test/cookbooks/dokken_test/README.md, test/cookbooks/dokken_test/metadata.rb, test/cookbooks/dokken_test/recipes/default.rb
This is the #1 error you run into with kitchen-dokken and the error is useless. Avoid the stacktrace and just toss a friendly error.
```
kitchen-dokken could not connect to the docker host at unix:///var/run/docker.sock. Is docker running?
```
=> Friendly error message when docker can't be reached

lib/kitchen/transport/dokken.rb
docker exec doesn't supply terminal width and height values to containers
currently. This should really be fixed upstream but this is workaround for the
issue until then. There's a 2 year old github issue for it so I doubt it's a
priority right now.
Before:
```
sme@megatron ~ stty size
48 151
sme@megatron ~ kitchen login
root@dokken:/# stty size
0 0
```
After:
```
sme@megatron ~ stty size
48 151
sme@megatron ~ kitchen login
root@dokken:/# stty size
48 151
```
refs:
- https://github.com/moby/moby/issues/33794
- https://github.com/moby/moby/issues/10341
Signed-off-by: Sean Escriva <sean.escriva@gmail.com>
=> Fix terminal size issue when using kitchen login

test/cookbooks/dokken_test/recipes/default.rb
the behavior for bundle install has changed.
We now need to provide the --path
See https://bugzilla.redhat.com/show_bug.cgi?id=1574594
=> fix the automatic tests

kitchen-dokken.gemspec
2.0 has no impact on this plugin
=> Loosen the Test-Kitchen dep to allow 2.0

.kitchen.yml, README.md, lib/kitchen/driver/dokken.rb, test/cookbooks/dokken_test/recipes/default.rb
enables testing of platforms with images that only/already exist locally (desirable for pre-push testing in CI or bandwidth preservation) by adding a config option to disable kitchen-dokken's currently required pre-test pull of the platform image.
obviates #139, fixes #138
=> Enable local image testing with a new pull_platform_image config

.travis.yml, lib/kitchen/provisioner/dokken.rb
I originally thought about deprecating the `chef_version` attribute in
the driver but instead opted to have this driver continue working like
customers expect. It is a weird case because it extends the ChefZero
provisioner but does not ever install chef - the driver selects a docker
image of chef to run. The license acceptance logic depends on
`product_version` being set to the correct version so we need to copy it
from the driver into the provisioner.
Replaces https://github.com/someara/kitchen-dokken/pull/177
=> Copy chef_version into provisioner so license acceptance works correctly

README.md, lib/kitchen/driver/dokken.rb, lib/kitchen/driver/dokken_version.rb
When your Docker daemon is running with user namespace remapping it is
not possible to run a privileged container unless you pass the
`--user-ns 'host'` flag. This PR add's the ability to pass that config
option to the container create call.
Signed-off-by: Elliott Davis <elliott@excellent.io>
=> Add ability to disable user namespace mode when running privileged containers

README.md, lib/kitchen/driver/dokken.rb
Right now if you specify latest or current chef images you won't ever get that image updated, which makes dokken not do what you'd expect. Now we pull on every run so you actually test on new versions. This does what you'd expect. If you want to turn it off there's a new config option: pull_chef_image
=> By default pull the chef docker image on every run

lib/kitchen/driver/dokken.rb
Previously, if you added an `env:` section to your driver config in `.kitchen.yml`, those variables we'ren't getting propagated to the eventual container. 
Signed-off-by: Josh Brand <jbrand@chef.io>
=> correct container env arg (env -> Env) to match driver config

lib/kitchen/provisioner/dokken.rb
This is bypassing the binstubs and breaking our tests in
buildkite.
=> Remove embedded from chef-client path

README.md, lib/kitchen/driver/dokken_version.rb, lib/kitchen/provisioner/dokken.rb
Hi, 👋 
I have a few cookbooks that download substantial amounts of remote files and having the `kitchen_sandbox` get cleaned after every `kitchen converge`. This massively increases converge time where we didn't have that issue on `kitchen-vagrant`. 
The PR adds an option to opt out of cleaning the kitchen sandbox. It defaults to do the cleaning, i.e. no changing existing behaviour. 
Thanks for reviewing,
Chris
=> Create option for leaving the kitchen sandbox between converges

README.md
This PR add a bit of documentation about how to include a CA authority from a  MITM proxy with openssl when using dokken behind this kind of proxy.
=> Add doc for internal CA and MITM proxy

.kitchen.yml, Gemfile, lib/kitchen/provisioner/dokken.rb
This fixes #194 and allows one to finally use enforce_idempotency and
multiple_converge with dokken. This is done by calling ``chef_cmd`` which
properly generates the code needed for adding enforce_idempotency and
multiple_converge.
To workaround an issue with ShellWords filtering out single quotes from
``chef_cmd``, the ``run_command`` gets written out as a file in the kitchen
sandbox and then executed directly.
Some other mix changes:
- Fix .kitchen.yml used for testing and switch to using CentOS 7 as the latest
Fedora was having issues and this should be more stable
- Fix .kitchen.yml so that Chef 15 and newer accept the license properly
- Replace pry-coolline with pry-byebug so that pry debugging works properly
Signed-off-by: Lance Albertson <lance@osuosl.org>
Describe what this …
=> Fix multiple_converge

README.md, lib/kitchen/driver/dokken.rb
Allows setting a memory limit in bytes in the driver block
=> Fixes #167 Allow configurable container memory limit

lib/kitchen/driver/dokken.rb, lib/kitchen/helpers.rb, lib/kitchen/transport/dokken.rb
Rubygems is very slow to traverse the filesystem when a dep is in fact
already loaded. Let's avoid that by gating many of the requires. This
also converts to .match? which avoids creating the whole match object.
=> Optimize our requires and use .match? not .match

lib/kitchen/helpers.rb
Consider the port as closed when the target network is either
unreachable or down as well. This can happen depending on the kitchen
hosts routing and the network it's connected to
=> Handle unreachable network errors

lib/kitchen/driver/dokken.rb
Fix a typo noticed in a CI failure on chef/chef.
> Failed to complete #create action: [work_image build failed: The command '/bin/sh -c yum install -y centos-release-scl' returned a non-zero code: 1. The common scenerios are incorrect intermediateinstructions such as not including `-y` on an `apt-get` or similar. The other common scenerio is a transient error such as an unresponsive mirror.] on end-to-end-centos-6
https://buildkite.com/chef-oss/chef-chef-master-verify/builds/7181#563d5663-bd03-4958-9cc8-b15272d9b2e0/778-794
=> Fix typo in error message.

lib/kitchen/driver/dokken.rb
Missed in #209. This error message reads awkwardly.
This error message incorrectly concatenates two lines without a space, resulting in `intermediateinstructions`.
> Failed to complete #create action: [work_image build failed: The command '/bin/sh -c yum install -y centos-release-scl' returned a non-zero code: 1. The common scenerios are incorrect intermediateinstructions such as not including `-y` on an `apt-get` or similar. The other common scenerio is a transient error such as an unresponsive mirror.] on end-to-end-centos-6
=> Fix bad concatenation in error message

README.md, lib/kitchen/provisioner/dokken.rb
This adds the same profile_ruby config from the chef-zero provisioner
=> Add profile_ruby config to match chef-zero

lib/kitchen/driver/dokken.rb
This PR extends the feature added in #218. Unfortunately there's a million
little places where docker decides to reach out to docker.io and if you
already have that image, or if you're not over you quota, it's hard to catch
it. This time I've done a lot of work to make sure every case is caught.
Further, the 'data image' doesn't get built unless you have a remote docker
host which I didn't in my testing, so that never got properly tested and was
broken when used with `docker_registry`, but it now works.
In addition I abstracted out a bit of the repetative code used to assemble
image names as well fixed some blatantly false debug messages, and added some
additional exceptions we weren't catching, plus filled in places we were
catching anything blindly.
The code is easier to read now, and …
=> Fix `docker_registry` plus some cleanups

lib/kitchen/helpers.rb, lib/kitchen/provisioner/dokken.rb
Explicitly sets `::Docker.url` from `default_docker_host` rather than relying on the underlying library logic https://github.com/swipely/docker-api/blob/master/lib/docker.rb#L71
Specifies binary file mode when creating `run_command` to suppress EOL CRLF conversion on Windows
#156 #183 #229
=> Fixes for Windows Execution

README.md, lib/kitchen/driver/dokken.rb
Adds an "aliases" parameter to the dokken driver that sets the same parameter in the Docker create request. This enables testing of cookbooks that depend on resolving multiple hostnames, such as cookbooks that configure multiple Apache virtual hosts.
None.
=> Add an hostname_aliases parameter

README.md, lib/kitchen/provisioner/dokken.rb
This matches the same change that went into Test Kitchen 2.12
=> Add the slow_resource_report config option

lib/kitchen/driver/dokken.rb
The `Docker::Image.create` method expects the credentials as the second argument and the connection as the third argument but this code is wrongly passing the connection in place of the credentials.
Passing the connection like this is causing it to be serialised as the `X-Registry-Auth` header which is then rejected by the server when using podman as the docker daemon.
=> Pass credentials hash when creating an image

README.md, kitchen.yml, lib/kitchen/driver/dokken.rb, lib/kitchen/helpers.rb, test/integration/ipv6/inspec/ipv6_spec.rb
This Adds IPv6 Support to the `dokken` network via the driver config. If the `ipv6` parameter is `true` then the network will enable ipv6 support and use the "2001:db8:1::/64" subnet on the `dokken` network. This subnet can be configured via the `ipv6_subnet` parameter. Documentation is also added in the README.md
None
=> Add IPv6 Support

CHANGELOG.md, lib/kitchen/driver/dokken_version.rb
Release 2.17.2
- Attempt to read ~/.docker/config.json for registry auths [@evandam](https://github.com/evandam)
https://github.com/test-kitchen/kitchen-dokken/issues/261
If you have not included a conventional commit message this can be fixed on merge.
=> Release 2.17.2

lib/kitchen/driver/dokken.rb
Check if ~/.docker/config.json exists before trying to parse credentials.
https://github.com/test-kitchen/kitchen-dokken/pull/262#issuecomment-1177232385
fix
=> check if ~/.docker/config.json exists

lib/kitchen/driver/dokken.rb
Docker Desktop 4.3.0+ uses cgroupv2 which breaks containers that use `systemd` ([ref](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-minor-changes-16))
> Containers that use `systemd` need to run with `--privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw.`
This PR provides the ability to do this with a new `cgroupns_host` option in kitchen.yml in the same way that `userns_host` works now.
**kitchen.yml example:**
```
---
driver:
name: dokken
privileged: true
cgroupns_host: true
volumes:
- /sys/fs/cgroup:/sys/fs/cgroup:rw
```
- https://github.com/test-kitchen/dokken-images/issues/57 
- https://chefcommunity.slack.com/archives/C2B6G1WCQ/p1658787465367899
Feature
=> add option to run container with --cgroupns=host

CHANGELOG.md, lib/kitchen/driver/dokken_version.rb
Release 2.17.4
- Add option to run container with --cgroupns=host [@drewhammond](https://github.com/drewhammond)
If you have not included a conventional …
=> Release 2.17.4

lib/kitchen/driver/dokken.rb
This is a draft/work-in-process proof of concept to address the idea mentioned in #268 
It allows users to specify either the following in a global config file.
```
---
driver:
platform: linux/amd64
```
or the following under a specific platform
```
platforms:
- name: ubuntu-20.04
driver:
image: dokken/ubuntu-20.04
platform: linux/amd64
``` 
#268 
- `_feat!_`:, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the !) and will result in …
=> Allow a user to specify a specific platform/architecture to use

lib/kitchen/driver/dokken.rb
While adding the support for different platforms/architecture in #272, some code fragments were removed accidentally
which causes the automatic reading of the `~/.docker/config.json` file to attempt the registry auth. 
This PR will revert those changes and will restore the functionality back. 
- …
=> Restore attempt to read config.json for registry auth

README.md, lib/kitchen/driver/dokken.rb
When using `docker_config_creds: true` this will use any [docker credential helpers](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) defined in `~/.docker/config.json`
In particular this makes it possible to use the [AWS ECR Docker Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper) to pull images from private ECR registries
This is related to the work I did ages ago on PR #189 and builds on #262
I would say this is a new feature.
note that there aren't any tests for the other features around docker credentials.
=> feat: use docker credential helpers to get auth

lib/kitchen/driver/dokken.rb, lib/kitchen/helpers.rb, lib/kitchen/provisioner/dokken.rb, lib/kitchen/transport/dokken.rb
When kitchen-dokken is run inside docker itself with the socket mounted in it fails for a number of reasons:
- Kitchen dokken will write files within $HOME/.dokken within the _container_, then attempt to bind bind that into the container being converged. Because bind mounts mount files/folders from the _host_ this will cause failure.
- If the docker instance is a docker-desktop instance (for example Docker for Mac) then the transport will resolve the incorrect address for the ssh connection
This change causes dokken to detect when it is run inside docker, and if it is it will aways use a data container. It will also connect to the data container using the internal "host.docker.internal" address if it detects the docker instance it is running is is a docker-desktop instance. 
List any …
=> feat: add support for running dokken in a container

kitchen.yml, lib/kitchen/driver/dokken.rb
Allows the `network_mode` setting to be a pre-defined network (such as `bridge` or `host`).
Without this, when the network mode is set to `host` or `bridge`, you get this error:
```
Failed to complete #create action: [{"message":"network-scoped alias is supported only for containers in user defined networks"}] on host-hello
```
Also, don't bother creating the `dokken` network if the `network_mode` is set to something else.
Fix
=> fix: do not set network aliases for host or bridge networks

lib/kitchen/driver/dokken.rb
It seems that Kitchen does not provide separate objects in all cases when doing concurrent execution. This means that mutating config[:binds] and config[:volumes] caused inconsistent state in concurrent actions.
We now copy these before mutating to avoid this.
I couldn't find any issues and just decided to fix it right away.
Just a fix
=> Avoid mutating config to fix concurrent execution

lib/kitchen/provisioner/dokken.rb
If clean_dokken_sandbox provisioner option is set to false, `kitchen converge` always exits with exit code 0 even if the chef-client run fails convergence. This is due to the return negating the exception that was raised.
#318 
bug fix
=> fix failed run exit code when clean_dokken_sandbox is false

lib/kitchen/helpers.rb
CentOS 7 was EOL yesterday and this is breaking all dokken workflows.
Signed-off-by: Lance Albertson <lance@osuosl.org>
Please describe what this change achieves
If you have not included a conventional commit message …
=> fix: Switch to using AlmaLinux 9 for the data container

lib/kitchen/driver/dokken.rb
This allows credentials for the default index to be used. In our case we have the business version of docker hub and get a 407 proxy error when we don't use user/pass via PAT token to auth to docker. As such we store the creds and this fix allows that situation to work.
- `_feat!_`:, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated …
=> fix: Use default registry credentials when they are set

.github/dependabot.yml, .markdownlint.yaml, README.md, lib/kitchen/transport/dokken.rb
Also sync over a few files
If you have not included a conventional commit message this can be fixed on merge.
=> Fix minor typos

lib/kitchen/driver/dokken.rb, lib/kitchen/helpers.rb, lib/kitchen/provisioner/dokken.rb
Fixed provisioner `root_path` configuration variable to change hardcoded paths.
All other kitchen drivers default to `/tmp/kitchen` it's harder to adapt cookbooks to allow for testing using `kitchen-dokken` when a default path changes to `/opt/kitchen` (escpecially when testing same cookbooks with both drivers), any idea/reason why it was changed to `/opt/kitchen` to begin with, maybe it should match other drivers for consistency?
Currently, setting `root_path` to anything else other than default value of `/tmp/kitchen` will fail as there's multiple hardcoded paths to `/opt/kitchen`
=> fix: provisioner root_path config option
